# Generated by Django 5.0.9 on 2024-10-24 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 23, 27, 42, 100013, tzinfo=datetime.timezone.utc)),
        ),
    ]
